# Iris Species Prediction using DecisionTree and RandomForestClassifier

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [53]:
df=pd.read_csv("C:\\Users\\saipr\\Downloads\\Iris.csv")

In [54]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [55]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset (assuming it's saved as 'iris.csv')
df = pd.read_csv('iris.csv')

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the 'Species' column
df['Species'] = label_encoder.fit_transform(df['Species'])

# Display the first few rows to verify
print(df.head())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0


# Train Test Split

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X = df.drop(['Id','Species'],axis=1)
y = df['Species']

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Decision Tree Classifier

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
dtree = DecisionTreeClassifier()

In [61]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

# Prediction and Evaluation

In [62]:
predictions = dtree.predict(X_test)

In [63]:
predictions

array([1, 1, 2, 0, 1, 1, 2, 0, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0,
       0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 0,
       2])

In [64]:
from sklearn.metrics import classification_report,confusion_matrix

In [65]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.80      1.00      0.89         8
           2       1.00      0.89      0.94        19

    accuracy                           0.96        45
   macro avg       0.93      0.96      0.94        45
weighted avg       0.96      0.96      0.96        45



In [66]:
print(confusion_matrix(y_test,predictions))

[[18  0  0]
 [ 0  8  0]
 [ 0  2 17]]


# Random Forest Classifier

# Training Model

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
rfc=RandomForestClassifier()

In [69]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

# Prediction and Evaluation

In [70]:
rcf_pred=rfc.predict(X_test)

In [71]:
rcf_pred

array([1, 1, 2, 0, 1, 1, 2, 0, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 0,
       2])

In [72]:
print(classification_report(y_test,rcf_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.89      1.00      0.94         8
           2       1.00      0.95      0.97        19

    accuracy                           0.98        45
   macro avg       0.96      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [73]:
print(confusion_matrix(y_test,rcf_pred))

[[18  0  0]
 [ 0  8  0]
 [ 0  1 18]]
